

parameters:
- name: MyMessage
  type: string
  default: "123!"
  
trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: echo "Building the project..."
      displayName: 'Build Step'
    - script: echo ${{parameters.MyMessage}}
      displayName: 'Print MyMessage'

- stage: Test
  jobs:
  - job: TestJob
    steps:
    - script: echo "Running tests..."
      displayName: 'Test Step'
    - script: echo ${{parameters.MyMessage}}
      displayName: 'Print MyMessage'

- stage: Deploy
  jobs:
  - deployment: DeploymentJob
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Deploying the application..."
            displayName: 'Deploy Step'
          - script: echo ${{parameters.MyMessage}}
            displayName: 'Print MyMessage'
