# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: MyMessage
  type: string
  default: "Hello, World!"
  displayName: 'Custom Message'
  
trigger:
- main

pool:
  vmImage: ubuntu-latest


steps:
- script: echo ${{parameters.MyMessage}}
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
